# Generated by Django 4.1.3 on 2022-12-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fridge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staged_ingr", models.CharField(max_length=200)),
                ("staged_amt", models.IntegerField()),
                ("ingredients", models.JSONField()),
                ("fridge_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipe_name", models.CharField(max_length=200)),
                ("recipe_URL", models.CharField(max_length=400)),
                ("ingredients", models.JSONField()),
            ],
        ),
    ]
